/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject.view;

import com.opencsv.exceptions.CsvValidationException;
import java.io.File;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import testproject.model.DatPhong;
import testproject.model.DocGhiFile;
import testproject.model.Phong;

/**
 *
 * @author HP
 */
public class ThanhToan extends javax.swing.JFrame {

    /**
     * Creates new form ThanhToan
     */
    DefaultTableModel tableModel;
    int id = 0;
   String trangThai="chưa thanh toán" ;
    List<DatPhong> listDP = new ArrayList<>();
    List<Phong> listP = new ArrayList<>();
    DocGhiFile docGhiFile = new DocGhiFile();
    private static final String curentDir = System.getProperty("user.dir");
    private static final String separator = File.separator;
    private static final String PATH_FILE_CSV_DatPhong = curentDir + separator + "data" + separator + "DatPhong.csv";
    private static final String PATH_FILE_CSV_PHONG = curentDir + separator + "data" + separator + "Phong.csv";
    public static File fileDP = new File(PATH_FILE_CSV_DatPhong);
    public static File fileP = new File(PATH_FILE_CSV_PHONG);

    public ThanhToan() {
        this.dispose();
       
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Nhập thông tin thanh toan");
        tableModel = (DefaultTableModel) btlDatPhong.getModel();

        if (fileDP.exists()) {
            try {
                listDP = docGhiFile.docFileDatPhong();
               
                hienTHi(listDP);
            } catch (CsvValidationException ex) {
                Logger.getLogger(DatPhongView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(DatPhongView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (fileP.exists()) {

            try {
                listP = docGhiFile.docFilePhong();
            } catch (CsvValidationException ex) {
                Logger.getLogger(DatPhongView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void hienTHi(List<DatPhong> DatPhong) {
        tableModel.setRowCount(0);
       
        for (DatPhong item : DatPhong) {
            String maDatPhong = item.getMaDatPhong();
            String maPhong = item.getMaPhong();
            String maKhachHang = item.getMaKhachHang();
            Date ngayDat = item.getNgayDat();
            Date ngayTra = item.getNgayTra();
            double thanhToan = item.getTongTien();
             trangThai=item.getTrangThai();
            tableModel.addRow(new Object[]{maDatPhong, maPhong, maKhachHang, ngayDat, ngayTra, thanhToan,   trangThai});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btlDatPhong = new javax.swing.JTable();
        btnThanhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btlDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Đặt phòng", "Mã Phòng", "Mã Khách Hàng", "Ngày Đặt ", "Ngày Trả", "Tổng Tiền", "Trạng Thái"
            }
        ));
        btlDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlDatPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(btlDatPhong);

        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 312, Short.MAX_VALUE)
                .addComponent(btnThanhToan)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlDatPhongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlDatPhongMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        int selectedRow = btlDatPhong.getSelectedRow();
        if (selectedRow >= 0) {
            String maDatPhong = (String) btlDatPhong.getValueAt(selectedRow, 0);
            String maPhong=(String) btlDatPhong.getValueAt(selectedRow, 1);
            for (DatPhong item : listDP) {
                if (maDatPhong.equals(item.getMaDatPhong())) {
                    item.setMaDatPhong(maDatPhong);
                    item.setMaPhong(maPhong);
                    item.setMaKhachHang(item.getMaKhachHang());
                    item.setNgayDat(item.getNgayDat());
                    item.setNgayTra(item.getNgayTra());
                    item.setTongTien(item.getTongTien());
                    item.setTrangThai("đã thanh toán");
                    JOptionPane.showConfirmDialog(null, "Đã thanh toán thành công\nXin cảm ơn", "Thông báo", JOptionPane.CLOSED_OPTION);
                   
                    for (Phong item1 : listP) {
                        if (item1.getMaPhong().equals(maPhong)) {
                            item1.setTrangThai("Con trong");
                        }
                    }
                       
                    
                    fileP.delete();
                    docGhiFile.ghiFilePhong(listP);
                    break;
                   
                     
                }
            }

            hienTHi(listDP);

        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlDatPhong;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
