/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testproject.view;

import com.opencsv.exceptions.CsvValidationException;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import testproject.model.DangKy;
import testproject.model.DocGhiFile;

/**
 *
 * @author phuon
 */
public class DangKyView extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    private List<DangKy> listDangKy = new ArrayList<>();
    private DocGhiFile docGhiFile = new DocGhiFile();
    private static final String curentDir = System.getProperty("user.dir");
    private static final String separator = File.separator;
    private static final String PATH_FILE_CSV_DANGKY = curentDir + separator + "data" + separator + "dangky.csv";
    private static File file = new File(PATH_FILE_CSV_DANGKY);
    private DateFormat df = new SimpleDateFormat("dd-MM-yyyy");

    public DangKyView() {
        initComponents();
        if (file.exists()) {
            try {
                listDangKy = docGhiFile.docFileDangKy();
            } catch (CsvValidationException ex) {
                Logger.getLogger(DangKyView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(DangKyView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void reSet() {
        txtHo.setText("");
        txtTen.setText("");
        txtTenDangNhap.setText("");
        txtMK.setText("");
        txtLaiMK.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMK = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        bnbHuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLaiMK = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        txtHo = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 220, 227));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Ký Tài Khoản Quản Trị Khách Sạn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 325, 228, 36));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tên Đăng Nhập:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 329, -1, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mật Khẩu: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 379, -1, 40));

        txtMK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 379, 228, 40));

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/icon_dangNHap.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 594, -1, -1));

        bnbHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnbHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/icon xoa (2).png"))); // NOI18N
        bnbHuy.setText("Hủy");
        bnbHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnbHuyActionPerformed(evt);
            }
        });
        getContentPane().add(bnbHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 598, -1, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Họ:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 216, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tên:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 276, -1, -1));

        txtLaiMK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtLaiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 445, 228, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ngày Sinh:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 503, -1, 40));

        txtNgaySinh.setDateFormatString("dd/MM/yyyy");
        txtNgaySinh.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNgaySinhAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 503, 228, 36));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Nhập lại MK:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 445, -1, 40));

        btnDangKy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/icon_dangKy.png"))); // NOI18N
        btnDangKy.setText("Đăng Ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 594, -1, -1));
        getContentPane().add(txtHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 228, 36));
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 228, 36));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/IconNguoi-Dk.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 64, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/nen-dangKy.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void bnbHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbHuyActionPerformed
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn hủy thông tin đang ký không?", "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        } else {
            DangNhap dn = new DangNhap();
            dn.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_bnbHuyActionPerformed
 
 

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtHo.getText().equals("")) {
            sb.append("Họ không được để trống\n");
        }
        if(txtTen.getText().equals("")){
            sb.append("Tên không được để trống\n");
        }
        if (txtMK.getText().equals("")) {
            sb.append("Mật Khẩu không được để trống\n");
        }
        if (txtTenDangNhap.getText().equals("")) {
            sb.append("Tên đăng nhập không được để trống\n");
        }
        if (txtLaiMK.getText().equals("")) {
            sb.append("Nhập lại mật khẩu không được để trống\n");
        }
        if (!txtLaiMK.getText().equals(txtMK.getText())) {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn nhập mật khẩu không khớp", "Backup problem", JOptionPane.WARNING_MESSAGE);
            txtLaiMK.requestFocus();
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(rootPane,
                    sb.toString(), "Backup problem", JOptionPane.WARNING_MESSAGE);
            return;
        }
    
            String ho = txtHo.getText();
            String ten = txtTen.getText();
            String tenDangNhap = txtTenDangNhap.getText();
            String mk = txtMK.getText();
            Date ngaySinh = txtNgaySinh.getDate();
            String ngaySinh1 = df.format(ngaySinh);
            DangKy dangky = new DangKy(ho, ten, tenDangNhap, mk, ngaySinh);
              listDangKy.add(dangky);
            file.delete();
            docGhiFile.ghiFileDangKy(listDangKy);
            JOptionPane.showConfirmDialog(rootPane, "Đăng ký tài khoản thành công\n Bây giờ bạn có thể đăng nhập", "Thông báo", JOptionPane.PLAIN_MESSAGE);
            reSet();
     
           
       


            
      
      
     
    
     
           
     
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát không?", "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        } else {
            DangNhap dn = new DangNhap();
            dn.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_formWindowClosed

    private void txtNgaySinhAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNgaySinhAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnbHuy;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtHo;
    private javax.swing.JPasswordField txtLaiMK;
    private javax.swing.JPasswordField txtMK;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
