/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testproject.view;

import com.opencsv.exceptions.CsvValidationException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import testproject.model.DatPhong;
import testproject.model.DocGhiFile;
import testproject.model.KhachHang;
import testproject.model.Phong;

/**
 *
 * @author phuon
 */
public class DoanhThu extends javax.swing.JFrame {

    /**
     * Creates new form DoanhThu
     */
    private DefaultTableModel tableModel;
    private int id = 0;
    private static final String curentDir = System.getProperty("user.dir");
    private static final String separator = File.separator;
    private static final String PATH_FILE_CSV_DATPHONG = curentDir + separator + "data" + separator + "DatPhong.csv";
    private static final String PATH_FILE_CSV_khachHang = curentDir + separator + "data" + separator + "KhachHang.csv";
    private static final String PATH_FILE_CSV_Phong = curentDir + separator + "data" + separator + "Phong.csv";

    private DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    private DateFormat df1 = new SimpleDateFormat("MM");

    private DocGhiFile dc = new DocGhiFile();
    private List<DatPhong> listDatPhong = new ArrayList<>();
    private List<KhachHang> listKH = new ArrayList<>();
    private List<Phong> listPhong = new ArrayList<>();

    private File fKH = new File(PATH_FILE_CSV_khachHang);
    private File fDP = new File(PATH_FILE_CSV_DATPHONG);
    private File fP = new File(PATH_FILE_CSV_Phong);

    private double tongtien = 0;

    public DoanhThu() {
        initComponents();
        tableModel = (DefaultTableModel) tblDatPhong.getModel();

        if (fKH.exists() && fDP.exists() && fP.exists()) {
            try {
                listDatPhong = dc.docFileDatPhong();
            } catch (CsvValidationException ex) {
                Logger.getLogger(DoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(DoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                listKH = dc.docFileKhachHang();
            } catch (CsvValidationException ex) {
                Logger.getLogger(DoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                listPhong = dc.docFilePhong();
            } catch (CsvValidationException ex) {
                Logger.getLogger(DoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void hienThiDatPhong(List<DatPhong> listDatPhong) {
        tableModel.setRowCount(0);
        for (DatPhong item : listDatPhong) {
            String maDatPhong = item.getMaDatPhong();
            String maphong = item.getMaPhong();
            String maKhachHang = item.getMaKhachHang();
            Date ngayDat = item.getNgayDat();
            String ngayDat1 = df.format(ngayDat);
            Date ngayTra = item.getNgayTra();
            String ngayTra1 = df.format(ngayTra);
            double tongTien = item.getTongTien();
            tableModel.addRow(new Object[]{maDatPhong, maphong, maKhachHang, ngayDat1, ngayTra1, tongTien});
        }
    }

    public void TongTienNgay() {
        tongtien=0;
        for (DatPhong item : listDatPhong) {
            if (df.format(item.getNgayTra()).equals(txtNgay.getText())) {
                tongtien += item.getTongTien();
            }
        }
    }

    public void TongTienThang() {
          tongtien=0;
        DateFormat format = new SimpleDateFormat("MM");
        for (DatPhong item : listDatPhong) {
            if (format.format(item.getNgayTra()).equals(txtNgay.getText())) {
                tongtien += item.getTongTien();
            }

        }
    }

    public static boolean isNumeric(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNgay = new javax.swing.JTextField();
        DoanhThu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatPhong = new javax.swing.JTable();
        DoanhThu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttongTien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNgay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 166, 251, 34));

        DoanhThu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DoanhThu.setText("Doanh Thu ngày");
        DoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoanhThuActionPerformed(evt);
            }
        });
        getContentPane().add(DoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 239, 170, 34));

        tblDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đặt phòng", "Mã phòng", "Mã khách hàng", "Ngày đặt", "Ngày trả", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatPhong);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 331, 991, 278));

        DoanhThu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DoanhThu1.setText("Doanh Thu tháng");
        DoanhThu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoanhThu1ActionPerformed(evt);
            }
        });
        getContentPane().add(DoanhThu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 239, -1, 34));

        jLabel1.setBackground(new java.awt.Color(255, 0, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Hệ Thống Tính Doanh Thu Của Khách Sạn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/icon_doanhThu3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 54, 120, 100));

        txttongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txttongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 627, 237, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tổng tiền:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/toppng.com-money-png-1000x1042.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 330));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/toppng.com-money-png-1000x1042.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 410, 330));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/back-arrow.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatPhongMouseClicked

    }//GEN-LAST:event_tblDatPhongMouseClicked

    private void DoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoanhThuActionPerformed
        tableModel.setRowCount(0);
        TongTienNgay();
        System.out.println(tongtien);
        txttongTien.setText(String.valueOf(tongtien));
        for (DatPhong item : listDatPhong) {
            System.out.println(df.format(item.getNgayTra()));
            if (txtNgay.getText().equals(df.format(item.getNgayTra()))) {
                String maDatPhong = item.getMaDatPhong();
                String maphong = item.getMaPhong();
                String maKhachHang = item.getMaKhachHang();
                Date ngayDat = item.getNgayDat();
                String ngayDat1 = df.format(ngayDat);
                Date ngayTra = item.getNgayTra();
                String ngayTra1 = df.format(ngayTra);
                double tongTien = item.getTongTien();
                
                tableModel.addRow(new Object[]{maDatPhong, maphong, maKhachHang, ngayDat1, ngayTra1, tongTien});
               
            }
        }
    }//GEN-LAST:event_DoanhThuActionPerformed

    private void DoanhThu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoanhThu1ActionPerformed
            tableModel.setRowCount(0);
        if (isNumeric(txtNgay.getText()) == true) {
            TongTienThang();
            System.out.println(tongtien);
            txttongTien.setText(String.valueOf(tongtien));
        }
        for (DatPhong item : listDatPhong) {
            if (txtNgay.getText().equals(df1.format(item.getNgayTra()))) {
                String maDatPhong = item.getMaDatPhong();
                String maphong = item.getMaPhong();
                String maKhachHang = item.getMaKhachHang();
                Date ngayDat = item.getNgayDat();
                String ngayDat1 = df.format(ngayDat);
                Date ngayTra = item.getNgayTra();
                String ngayTra1 = df.format(ngayTra);
                double tongTien = item.getTongTien();
                tableModel.addRow(new Object[]{maDatPhong, maphong, maKhachHang, ngayDat1, ngayTra1, tongTien});
            }
        }

    }//GEN-LAST:event_DoanhThu1ActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        close();
          new Menu().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked
public void close(){
       WindowEvent closeWindow= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
   }
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoanhThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoanhThu;
    private javax.swing.JButton DoanhThu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatPhong;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txttongTien;
    // End of variables declaration//GEN-END:variables
}
