/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject.view;

import com.opencsv.exceptions.CsvValidationException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.net.www.content.audio.x_aiff;
import testproject.model.DocGhiFile;
import testproject.model.HoComparator;
import testproject.model.KhachHang;
import testproject.model.MaKhachHangComparator;
import testproject.model.TuoiComparator;

/**
 *
 * @author phuon
 */
public class NhapThongTinKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form NhapThongTinKhachHang
     */
    private DefaultTableModel tableModel;
    private int id = 0;
    private List<KhachHang> listKH = new ArrayList<>();
    private DocGhiFile docGhiFile = new DocGhiFile();
    private static final String curentDir = System.getProperty("user.dir");
    private static final String separator = File.separator;
    private static final String PATH_FILE_CSV = curentDir + separator + "data" + separator + "KhachHang.csv";
    private static File f = new File(PATH_FILE_CSV);

    public NhapThongTinKhachHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Nhập thông tin khách hàng");
        tableModel = (DefaultTableModel) tblKhachHang.getModel();
         if (f.exists()) {
            try {
                listKH = docGhiFile.docFileKhachHang();
                if(listKH.size()==0){
                    f.delete();
                    NhapThongTinKhachHang kh = new NhapThongTinKhachHang();
                    kh.setVisible(true);
                }
                else{
                    String ma = listKH.get(listKH.size() - 1).getMaKhachHang();
                    id = Integer.parseInt(ma.substring(2)) + 1;
                    hienThi(listKH);
                }
                
            } catch (CsvValidationException ex) {
                Logger.getLogger(NhapThongTinKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void hienThi(List<KhachHang> listKH) {
        tableModel.setRowCount(0);
        for (KhachHang item : listKH) {
            String maKhachHang = item.getMaKhachHang();
            String hoTen = item.getHoTen();
            String soDt = item.getSDT();
            int tuoi = item.getTuoi();
            String cmnd = item.getCMND();
            String pttt = item.getPhuongThucThanhToan();
            tableModel.addRow(new Object[]{maKhachHang, hoTen, cmnd, soDt, tuoi, pttt});
        }
    }

    public void resetForm() {
        txtCMND.setText("");
        txtHoTen.setText("");
        txtSDT.setText("");
        txtTuoi.setText("");
    }

    public static boolean isNumeric(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnThemThongTin = new javax.swing.JButton();
        btnChinhSua = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        boxPhuongThuThanhToan = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        boxSapXep = new javax.swing.JComboBox<>();
        btnReSet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 220, 227));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập Thông Tin Khách Hàng ");

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/iconBaack.png"))); // NOI18N
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnQuayLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1248, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Họ và tên: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 118, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("CMND: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 183, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("SĐT: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 244, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 0));
        jLabel6.setText("Tuổi:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 0));
        jLabel7.setText("Thanh toán: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 177, -1, -1));

        txtHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoTenFocusLost(evt);
            }
        });
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 114, 240, 33));

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });
        getContentPane().add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 172, 240, 33));

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 233, 240, 33));

        txtTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuoiActionPerformed(evt);
            }
        });
        getContentPane().add(txtTuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 240, 33));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ Tên", "CMND", "SĐT", "Tuổi ", "PTTT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);
        if (tblKhachHang.getColumnModel().getColumnCount() > 0) {
            tblKhachHang.getColumnModel().getColumn(0).setMinWidth(50);
            tblKhachHang.getColumnModel().getColumn(0).setMaxWidth(100);
            tblKhachHang.getColumnModel().getColumn(1).setMinWidth(250);
            tblKhachHang.getColumnModel().getColumn(1).setMaxWidth(350);
            tblKhachHang.getColumnModel().getColumn(2).setMinWidth(200);
            tblKhachHang.getColumnModel().getColumn(2).setMaxWidth(300);
            tblKhachHang.getColumnModel().getColumn(4).setMinWidth(50);
            tblKhachHang.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 369, 1248, 438));

        btnThemThongTin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/sign-add-icon.png"))); // NOI18N
        btnThemThongTin.setText("Thêm thông tin ");
        btnThemThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThongTinActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        btnChinhSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/icons8-pencil-48.png"))); // NOI18N
        btnChinhSua.setText("Chỉnh sửa");
        btnChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        btnSapXep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/icon-sapxep.png"))); // NOI18N
        btnSapXep.setText("Sắp xếp ");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });
        getContentPane().add(btnSapXep, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 290, -1, -1));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/icons8-trash-48.png"))); // NOI18N
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        boxPhuongThuThanhToan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boxPhuongThuThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Thẻ" }));
        boxPhuongThuThanhToan.setToolTipText("");
        boxPhuongThuThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(boxPhuongThuThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 172, 240, 33));

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/iconTimKiem.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, -1, -1));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 150, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 0));
        jLabel8.setText("Chức năng:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        boxSapXep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boxSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tuoi", "Ho", "Ma KH" }));
        boxSapXep.setToolTipText("");
        boxSapXep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(boxSapXep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, 90, 33));

        btnReSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/iconLamMoi.png"))); // NOI18N
        btnReSet.setText("Reset");
        btnReSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReSetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/view/icon/nen-gioithieu.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1250, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuoiActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed
    public boolean checkCMND(String text){
        for(KhachHang x :listKH){
            if(x.getCMND().equals(text)){
                return false ;
            }
        }
        return true ;
    }
    public  boolean checkTenKH(String text){
        String specialCharacters = "!#$%&'()*+,-./:;<=>?@[]^_`{|}~0123456789";
           
    String[] strlCharactersArray = new String[ text.length()];
    for (int i = 0; i <  text.length(); i++) {
         strlCharactersArray[i] = Character
            .toString( text.charAt(i));
    }
    //now  strlCharactersArray[i]=[A, d, i, t, y, a]
    int count = 0;
    for (int i = 0; i <  strlCharactersArray.length; i++) {
        if (specialCharacters.contains( strlCharactersArray[i])) {
            count++;
        }

    }
    if(count==0){
       return true ;
        
    }
    else{
       return false ;
    }

    }
    private void btnChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtHoTen.getText().equals("")) {
            sb.append("Mã khách hàng không được để trống\n");
        }
        if (txtCMND.getText().equals("")) {
            sb.append("Số chứng minh nhân dân  không được để trống\n");
        }
        if (txtSDT.getText().equals("")) {
            sb.append("Số điện thoại không được để trống\n");
        }
        if (txtTuoi.getText().equals("")) {
            sb.append("Tuổi không được để trống\n");
        }
          if(txtSDT.getText().length()<10){
              sb.append("sdt phải lớn hơn 10 số\n");
        }
        if(txtCMND.getText().length()<12 ||txtCMND.getText().length()>12 ){
            sb.append("chứng minh nhân dân hay thẻ căn cước phải số đủ 12 số");
        }
        if(checkTenKH(txtHoTen.getText())==false){
             
      JOptionPane.showConfirmDialog(null,"Tên khách hàng chứa ký tự đặc biệt\nHãy nhớ tên chỉ chứa ký tự a-z A-Z và không chứa dấu","thông báo",JOptionPane.ERROR_MESSAGE);
        return ;             
     }
        
         if (sb.length() > 0) {
            JOptionPane.showMessageDialog(rootPane,
                    sb.toString(), "Backup problem", JOptionPane.WARNING_MESSAGE);
            return;
        }
//        
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn chỉnh sửa thông tin không?", "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        String maKhachHang = "KH" + id++;
        String HotenKhachHang = txtHoTen.getText();
        String phuongTTT = boxPhuongThuThanhToan.getSelectedItem().toString();
        String scmnd=null, sdt = null ;
        int tuoi =0 ;
           try {
             scmnd = "0"+Long.parseLong(txtCMND.getText());
         //     Long.parseLong(txtCMND.getText());
        } catch (NumberFormatException e) {
           
         
           JOptionPane.showConfirmDialog(null,"Số chứng minh thư hoặc thẻ căn cước đã bị nhập sai định dạng\n xin vui lòng nhập sô","thông báo",JOptionPane.CLOSED_OPTION);
        }
      
        try {
            sdt =  "0"+ Long.parseLong(txtSDT.getText());
           } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Số điện thoại đã bị nhập sai định dạng\n xin vui lòng nhập sô","thông báo",JOptionPane.CLOSED_OPTION);
        }
          try {
            tuoi= Integer.parseInt(txtTuoi.getText());
        } catch (Exception e) {
             JOptionPane.showConfirmDialog(null,"Tuổi đã bị nhập sai định dạng\n xin vui lòng nhập sô","thông báo",JOptionPane.CLOSED_OPTION);
            
        }
      
       int check = 0;
        int selectedRow = tblKhachHang.getSelectedRow();
        String maKH = (String) tblKhachHang.getValueAt(selectedRow, 0);
        for (KhachHang item : listKH) {
            if (item.getMaKhachHang().equals(maKH)) {
                item.setHoTen(HotenKhachHang);
                item.setTuoi(tuoi);
                item.setCMND(scmnd);
                item.setSDT(sdt);
                item.setPhuongThucThanhToan(phuongTTT);
                check = 1;
                break;
            }

        }
        
        if (check == 1) {
            if (scmnd == null || sdt == null || tuoi == 0) {
                System.out.println("Loi");
            } else {
                if (tuoi >= 14) {
//                    if(checkCMND(scmnd)){
                     f.delete();
                        docGhiFile.ghiFileKhachHang(listKH);
                        hienThi(listKH);
                        resetForm();
                        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");   
 //                   }
//                    else{
//                   JOptionPane.showConfirmDialog(null, "Số chứng minh nhân dân hay thẻ căn cước bị trùng\n xin vui lòng check lại thông  tin", "thông báo", JOptionPane.CLOSED_OPTION);      
//                    }
                    
                } else {
                    JOptionPane.showConfirmDialog(null, "Khách hàng Chưa đủ tuôi\n Khách hàng phải lớn hơn 14 tuổi", "thông báo", JOptionPane.CLOSED_OPTION);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Thông tin Khách hàng không tồn tại", "Backup problem", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_btnChinhSuaActionPerformed
// thêm thoogn tin 
    private void btnThemThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThongTinActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtHoTen.getText().equals("")) {
            sb.append("Mã khách hàng không được để trống\n");
        }
        if (txtCMND.getText().equals("")) {
            sb.append("Số chứng minh nhân dân  không được để trống\n");
        }
        if (txtSDT.getText().equals("")) {
            sb.append("Số điện thoại không được để trống\n");
        }
        if (txtTuoi.getText().equals("")) {
            sb.append("Tuổi không được để trống\n");
        }
        if (txtSDT.getText().length() < 10) {
            sb.append("sdt phải lớn hơn 10 số\n");
        }
        if (txtCMND.getText().length() < 12 || txtCMND.getText().length() > 12) {
            sb.append("chứng minh nhân dân hay thẻ căn cước phải số đủ 12 số");
            txtCMND.requestFocus();
            return ;
        }
          if(checkCMND(txtCMND.getText())==false){
                JOptionPane.showConfirmDialog(null, "Số chứng minh nhân dân hay thẻ căn cước bị trùng\n xin vui lòng check lại thông  tin", "thông báo", JOptionPane.CLOSED_OPTION);
               txtHoTen.requestFocus();
               return ;
         
         }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(rootPane,
                    sb.toString(), "Backup problem", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //kiểm tra sau khi xóa 
        int max = 0;
        for (KhachHang item : listKH) {
            if (Integer.parseInt(item.getMaKhachHang().substring(2)) > max) {
                max = Integer.parseInt(item.getMaKhachHang().substring(2));
                id = max + 1;
            }
        }
        String maKhachHang = "KH" + id++;
        String HotenKhachHang = txtHoTen.getText();
        String phuongTTT = boxPhuongThuThanhToan.getSelectedItem().toString();
        String scmnd = null, sdt = null;
        int tuoi = 0;
        try {
            scmnd = "0" + Long.parseLong(txtCMND.getText());
            //     Long.parseLong(txtCMND.getText());
        } catch (NumberFormatException e) {

            JOptionPane.showConfirmDialog(null, "Số chứng minh thư hoặc thẻ căn cước đã bị nhập sai định dạng\n xin vui lòng nhập sô", "thông báo", JOptionPane.CLOSED_OPTION);
        }
        try {
            tuoi = Integer.parseInt(txtTuoi.getText());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Tuổi đã bị nhập sai định dạng\n xin vui lòng nhập sô", "thông báo", JOptionPane.CLOSED_OPTION);

        }

        try {
            sdt = "0" + Long.parseLong(txtSDT.getText());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Số điện thoại đã bị nhập sai định dạng\n xin vui lòng nhập sô", "thông báo", JOptionPane.CLOSED_OPTION);
        }

        if (scmnd == null || sdt == null || tuoi == 0) {
            System.out.println("Loi");
        } 
        else {
            if (tuoi >= 14) {
                 KhachHang kh = new KhachHang(maKhachHang, HotenKhachHang, scmnd, sdt, tuoi, phuongTTT);
                    listKH.add(kh);
                    tableModel.addRow(new Object[]{maKhachHang, HotenKhachHang, scmnd, sdt, tuoi, phuongTTT});
                    f.delete();
                    docGhiFile.ghiFileKhachHang(listKH);
                    resetForm();

            } else {
                JOptionPane.showConfirmDialog(null, "Khách hàng Chưa đủ tuôi\n Khách hàng phải lớn hơn 14 tuổi", "thông báo", JOptionPane.CLOSED_OPTION);
            }
        }


    }//GEN-LAST:event_btnThemThongTinActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void txtHoTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoTenFocusLost

    }//GEN-LAST:event_txtHoTenFocusLost
//kích ở bảng để hiện ra thông tin 
    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        int selectedRow = tblKhachHang.getSelectedRow();
        if (selectedRow >= 0) {
            String maKhachHang = (String) tblKhachHang.getValueAt(selectedRow, 0);
            for (KhachHang item : listKH) {
                if (item.getMaKhachHang().equals(maKhachHang)) {
                    txtHoTen.setText(item.getHoTen());
                    txtSDT.setText(item.getSDT());
                    txtCMND.setText(item.getCMND());
                    txtTuoi.setText(Integer.toString(item.getTuoi()));
                    boxPhuongThuThanhToan.setSelectedItem(item.getPhuongThucThanhToan());
                    break;
                }
            }
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        boolean flag = false;
        tableModel.setRowCount(0);
        if (isNumeric(txtTimKiem.getText()) == false) {
            for (KhachHang item : listKH) {
                if (item.getMaKhachHang().equals(txtTimKiem.getText())) {
                    tableModel.addRow(new Object[]{item.getMaKhachHang(), item.getHoTen(), item.getCMND(), item.getSDT(), item.getTuoi(), item.getPhuongThucThanhToan()});
                }
                if (item.getHoTen().equals(txtTimKiem.getText())) {
                    System.out.println("a");
                    tableModel.addRow(new Object[]{item.getMaKhachHang(), item.getHoTen(), item.getCMND(), item.getSDT(), item.getTuoi(), item.getPhuongThucThanhToan()});
                }
                if (item.getSDT().equals(txtTimKiem.getText())) {
                    tableModel.addRow(new Object[]{item.getMaKhachHang(), item.getHoTen(), item.getCMND(), item.getSDT(), item.getTuoi(), item.getPhuongThucThanhToan()});
                }
                flag = true;
            }
            if (flag == false) {
                JOptionPane.showMessageDialog(rootPane,
                        "Thông tin Khách hàng không tồn tại", "Backup problem", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            for (KhachHang item : listKH) {
                if (item.getCMND().equals(txtTimKiem.getText())) {
                    tableModel.addRow(new Object[]{item.getMaKhachHang(), item.getHoTen(), item.getCMND(), item.getSDT(), item.getTuoi(), item.getPhuongThucThanhToan()});
                }
                if (item.getSDT().equals(txtTimKiem.getText())) {
                    tableModel.addRow(new Object[]{item.getMaKhachHang(), item.getHoTen(), item.getCMND(), item.getSDT(), item.getTuoi(), item.getPhuongThucThanhToan()});
                }
                if (txtTimKiem.getText().length() <= 2 && txtTimKiem.getText().length() != 0) {
                    if (item.getTuoi() == Integer.parseInt(txtTimKiem.getText())) {
                        tableModel.addRow(new Object[]{item.getMaKhachHang(), item.getHoTen(), item.getCMND(), item.getSDT(), item.getTuoi(), item.getPhuongThucThanhToan()});
                    }
                }
                flag = true;
            }
            if (flag == false) {
                JOptionPane.showMessageDialog(rootPane,
                        "Thông tin Khách hàng không tồn tại", "Backup problem", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        if (boxSapXep.getSelectedItem().toString().equals("Tuoi")) {
            Collections.sort(listKH, new TuoiComparator());
            hienThi(listKH);
        }
        if (boxSapXep.getSelectedItem().toString().equals("Ho")) {
            Collections.sort(listKH, new HoComparator());
            hienThi(listKH);
        }
        if (boxSapXep.getSelectedItem().toString().equals("Ma KH")) {
            Collections.sort(listKH, new MaKhachHangComparator());
            hienThi(listKH);
        }
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tblKhachHang.getSelectedRow();
        String maPhong = (String) tblKhachHang.getValueAt(selectedRow, 0);
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa  thông tin phòng  không?", "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        int check = 0;
        for (int i = 0; i < listKH.size(); i++) {
            if (listKH.get(i).getMaKhachHang().equals(maPhong)) {
                listKH.remove(listKH.get(i));
                check = 1;
                break;
            }
        }

        f.delete();
        docGhiFile.ghiFileKhachHang(listKH);
        hienThi(listKH);
        resetForm();
        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnReSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReSetActionPerformed
       txtCMND.setText("");
       txtHoTen.setText("");
       txtSDT.setText("");
       txtTuoi.setText("");
       txtTimKiem.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReSetActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
      // TODO add your handling code here:
        close();
          new Menu().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed
public void close(){
       WindowEvent closeWindow= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapThongTinKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxPhuongThuThanhToan;
    private javax.swing.JComboBox<String> boxSapXep;
    private javax.swing.JButton btnChinhSua;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnReSet;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnThemThongTin;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
